name: robert-stage9-petitradtrans
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - numpy=2.2.6
  - scipy
  - h5py
  - astropy>=6.0
  - pydantic>=2.7
  - pyyaml>=6.0
  - synphot>=1.6
  - stsynphot>=1.4
  - matplotlib
  - mpich=4.3
  - mpi4py=4.1.2
  - multinest=3.10
  - pymultinest=2.12
  - fortran-compiler
  - meson-python
  - ninja
  - pip:
      - petitRADTRANS==3.3.3
