"""Opacity metadata, inspectors, and fixture interfaces."""

from .archive import (
    RobertOpacityArchive,
    inspect_robert_npy_directory,
    inspect_robert_npz_archive,
    load_robert_npy_directory,
    load_robert_npz_archive,
    write_robert_npy_directory,
    write_robert_npz_archive,
)
from .correlated_k import (
    CorrelatedKCoverageReport,
    CorrelatedKOpacityProvider,
    CorrelatedKTable,
    EvaluatedCorrelatedKOpacity,
    PreparedCorrelatedKOpacity,
)
from .inspectors import (
    file_sha256,
    inspect_exomol_directory,
    inspect_hitran_cia_file,
    inspect_hitran_par_file,
    inspect_kta_file,
)
from .kta import (
    KtaHeader,
    KtaTable,
    convert_kta_to_robert_archive,
    kta_product_from_header,
    read_kta,
    read_kta_header,
)
from .metadata import (
    GridCoverage,
    OpacityCoverageReport,
    OpacityDatabase,
    OpacityDataProduct,
    OpacityDataSource,
    OpacityMode,
    OpacityStorageFormat,
    SpectralCoverage,
    pressure_values_in_unit,
    spectral_grid_values_in_unit,
)

__all__ = [
    "CorrelatedKCoverageReport",
    "CorrelatedKOpacityProvider",
    "CorrelatedKTable",
    "EvaluatedCorrelatedKOpacity",
    "GridCoverage",
    "KtaHeader",
    "KtaTable",
    "OpacityCoverageReport",
    "OpacityDatabase",
    "OpacityDataProduct",
    "OpacityDataSource",
    "OpacityMode",
    "OpacityStorageFormat",
    "PreparedCorrelatedKOpacity",
    "RobertOpacityArchive",
    "SpectralCoverage",
    "convert_kta_to_robert_archive",
    "file_sha256",
    "inspect_exomol_directory",
    "inspect_hitran_cia_file",
    "inspect_hitran_par_file",
    "inspect_kta_file",
    "inspect_robert_npy_directory",
    "inspect_robert_npz_archive",
    "load_robert_npy_directory",
    "load_robert_npz_archive",
    "kta_product_from_header",
    "pressure_values_in_unit",
    "read_kta",
    "read_kta_header",
    "spectral_grid_values_in_unit",
    "write_robert_npy_directory",
    "write_robert_npz_archive",
]
