extends: ../../../wasp80b_mie_direct_nk_pg14_R1000.yaml

run:
  name: n-k
  description: WASP-80b homogeneous one-region direct-n/k Mie cloud retrieval using all native datasets.

disk_emission:
  model: one_region

sampler:
  engine: multinest
  live_points: 1000
  multinest_max_iterations: 0
  resume: resume
  show_status: false
  seed: 8005

runtime:
  mpi_processes: 128

plotting:
  enabled: true
