"""ROBERT: a foundation for JWST exoplanet emission retrievals."""

from .atmosphere import (
    AtmosphereBuilder,
    AtmosphereState,
    BackgroundGasMixture,
    ChemistryModel,
    CompositionMeanMolecularWeight,
    ConstantChemistry,
    FixedMeanMolecularWeight,
    FreeChemistry,
    IsothermalTemperatureProfile,
    MadhusudhanSeager2009TemperatureProfile,
    MeanMolecularWeightModel,
    ParmentierGuillot2014TemperatureProfile,
    SplineTemperatureProfile,
    TabulatedTemperatureProfile,
    TemperatureProfile,
)
from .bodies import Planet, Star
from .core import PressureGrid, SpectralGrid, Spectrum
from .diagnostics import (
    EmissionBenchmark,
    OpacityComparisonResult,
    TimingResult,
    blackbody_eclipse_depth,
    blackbody_eclipse_depth_spectrum,
    compare_opacity_arrays,
    load_emission_benchmark_csv,
    planck_radiance_wavelength,
    time_callable,
)
from .forward import ForwardModel, ModelPrediction, PlaceholderEmissionBackend
from .instruments import LinearObservationResponse, Observation, PreparedObservationResponse
from .io import AtmosphereModelSetup, RobertConfig, build_atmosphere_setup
from .likelihoods import GaussianLikelihood
from .opacity import (
    CoverageReport,
    CorrelatedKCoverageReport,
    CorrelatedKOpacityProvider,
    CorrelatedKTable,
    EvaluatedOpacity,
    EvaluatedCorrelatedKOpacity,
    FixtureOpacityProvider,
    GridCoverage,
    NemesisKTable,
    NemesisKTableHeader,
    OpacityCoverageReport,
    OpacityDatabase,
    OpacityDataProduct,
    OpacityDataSource,
    OpacityMode,
    OpacityStorageFormat,
    PreparedOpacity,
    PreparedCorrelatedKOpacity,
    RobertOpacityArchive,
    SpectralCoverage,
    convert_kta_to_robert_archive,
    inspect_exomol_directory,
    inspect_hitran_cia_file,
    inspect_hitran_par_file,
    inspect_kta_file,
    inspect_robert_npy_directory,
    inspect_robert_npz_archive,
    load_robert_npy_directory,
    load_robert_npz_archive,
    kta_product_from_header,
    read_kta,
    read_kta_header,
    write_robert_npy_directory,
    write_robert_npz_archive,
)
from .retrieval import (
    EmissionModel,
    RetrievalConfig,
    RetrievalResult,
    run_stub_retrieval,
)
from .rt import GasOpticalDepth, assemble_gas_optical_depth

__all__ = [
    "AtmosphereBuilder",
    "AtmosphereModelSetup",
    "AtmosphereState",
    "BackgroundGasMixture",
    "ChemistryModel",
    "CompositionMeanMolecularWeight",
    "ConstantChemistry",
    "CoverageReport",
    "CorrelatedKCoverageReport",
    "CorrelatedKOpacityProvider",
    "CorrelatedKTable",
    "EmissionModel",
    "EmissionBenchmark",
    "EvaluatedOpacity",
    "EvaluatedCorrelatedKOpacity",
    "FixtureOpacityProvider",
    "FixedMeanMolecularWeight",
    "ForwardModel",
    "FreeChemistry",
    "GasOpticalDepth",
    "GaussianLikelihood",
    "GridCoverage",
    "IsothermalTemperatureProfile",
    "LinearObservationResponse",
    "MadhusudhanSeager2009TemperatureProfile",
    "MeanMolecularWeightModel",
    "ModelPrediction",
    "NemesisKTable",
    "NemesisKTableHeader",
    "Observation",
    "OpacityCoverageReport",
    "OpacityDatabase",
    "OpacityDataProduct",
    "OpacityDataSource",
    "OpacityMode",
    "OpacityStorageFormat",
    "OpacityComparisonResult",
    "ParmentierGuillot2014TemperatureProfile",
    "Planet",
    "PlaceholderEmissionBackend",
    "PressureGrid",
    "PreparedObservationResponse",
    "PreparedOpacity",
    "PreparedCorrelatedKOpacity",
    "RobertOpacityArchive",
    "RobertConfig",
    "RetrievalConfig",
    "RetrievalResult",
    "SplineTemperatureProfile",
    "SpectralGrid",
    "Spectrum",
    "Star",
    "TabulatedTemperatureProfile",
    "TemperatureProfile",
    "TimingResult",
    "SpectralCoverage",
    "blackbody_eclipse_depth",
    "blackbody_eclipse_depth_spectrum",
    "build_atmosphere_setup",
    "assemble_gas_optical_depth",
    "compare_opacity_arrays",
    "convert_kta_to_robert_archive",
    "inspect_exomol_directory",
    "inspect_hitran_cia_file",
    "inspect_hitran_par_file",
    "inspect_kta_file",
    "inspect_robert_npy_directory",
    "inspect_robert_npz_archive",
    "load_robert_npy_directory",
    "load_robert_npz_archive",
    "load_emission_benchmark_csv",
    "kta_product_from_header",
    "planck_radiance_wavelength",
    "read_kta",
    "read_kta_header",
    "run_stub_retrieval",
    "time_callable",
    "write_robert_npy_directory",
    "write_robert_npz_archive",
]

__version__ = "0.3.0"
